workdir: /storage1/victor/speedypipe4meta

threads: 16
mem_mb: 256000

# MEGAHIT parameters
megahit:
    klist: '65'

# KRAKEN parameters
kraken:
    db: '/usr/local/kraken2/db_standard'

samples:
    'M1':
        forward: 'data/M1_1.fq.gz'
        revers: 'data/M1_2.fq.gz'

# Mininum length of contigs
contigs:
    minlength: 200
